name = "mitrachain/transaction-logger"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'mitrachain/transaction-logger'"

[repository]
user = "mitrachain"
project = "transaction-logger"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
